version: "3"

services:
  app:
    build: .
    image: jnk5y/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
