version: "3"

services:
  app:
    #image: jnk5y/shepherd
    image: shepherd-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      TZ: 'US/Eastern'
      SLEEP_TIME: '10m'
      FILTER_SERVICES: ''
      VERBOSE: 'false'
    restart: unless-stopped
