version: "3"

services:
  app:
    image: jnk5y/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
    environment:
      TZ: 'America/New_York'
      SLEEP_TIME: '10m'
      FILTER_SERVICES: ''
    restart: unless-stopped
